language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
addons:
  sonarcloud:
    organization: "madsciencist-github" # the key of the org you chose at step #3
branches:
  only:
    - master
    - develop
install:
  - dotnet restore
script:
 - dotnet build
 - dotnet test test/SmartHome.UnitTests/SmartHome.UnitTests.csproj
 - sonar-scanner -Dsonar.verbose=true -X
notifications:
  email:
    on_success: never
    on_failure: always
