language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
addons:
  sonarcloud:
    organization: "madsciencist-github"
    token:
      secure: $SONAR_TOKEN
branches:
  only:
    - develop
    - master
install:
  - dotnet tool install --global dotnet-sonarscanner
  - dotnet restore
before_script:
  - export PATH="$PATH:$HOME/.dotnet/tools"
script:
 - dotnet sonarscanner begin /k:"MadSciencist_SmartHomeAPI" /n:"SmartHomeAPI" /v:"1.0.0" /o:"madsciencist-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR_TOKEN" /d:sonar.language="cs" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.cs.opencover.reportsPaths="lcov.opencover.xml" || true
 - dotnet build
 - dotnet test test/SmartHome.UnitTests/SmartHome.UnitTests.csproj
 - dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN" || true
notifications:
  email:
    on_success: never
    on_failure: always
cache:
  directories:
    - '$HOME/.nuget/packages'