language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
branches:
  only:
    - master
install:
  - dotnet restore
 script
 - dotnet build
 - dotnet test test/SmartHome.UnitTests/SmartHome.UnitTests.csproj
notifications:
  email:
    on_success: never
    on_failure: always
