language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
addons:
  sonarcloud:
    organization: "madsciencist-github"
    token:
      secure: $SONAR_TOKEN
branches:
  only:
    - develop
    - master
install:
  - dotnet tool install --global dotnet-sonarscanner
  - dotnet restore
before_script:
  - export PATH="$PATH:$HOME/.dotnet/tools"
script:
 - dotnet sonarscanner begin /k:"MadSciencist_SmartHomeAPI" /n:"SmartHomeAPI" /v:"1.0.0" /o:"madsciencist-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR_TOKEN" /d:sonar.language="cs" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.cs.opencover.reportsPaths="lcov.opencover.xml" || true
 - dotnet build
 - dotnet test --no-build test/SmartHome.API.Tests/SmartHome.API.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 - curl -s https://codecov.io/bash > codecov
 - chmod +x codecov
 - ./codecov -f "SmartHome_coverage.xml" -t $CODECOV_TOKEN
before_deploy: 
  - bash ./scripts/CI/deploy.sh
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: ./smart_home_api_release_linux_arm.tar.gz
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    on_success: never
    on_failure: always
cache:
  directories:
    - '$HOME/.nuget/packages'
