// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHome.Core.Data;

namespace SmartHome.Core.Data.Migrations
{
    [DbContext(typeof(EntityFrameworkContext))]
    [Migration("20191022173716_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<int>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SmartHome.Core.Entities.DictionaryEntity.Dictionary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Metadata");

                    b.Property<string>("Name");

                    b.Property<bool>("ReadOnly");

                    b.Property<byte[]>("RowVersion");

                    b.HasKey("Id");

                    b.ToTable("tbl_dictionary");
                });

            modelBuilder.Entity("SmartHome.Core.Entities.DictionaryEntity.DictionaryValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DictionaryId");

                    b.Property<string>("DisplayValue");

                    b.Property<string>("InternalValue");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<string>("Metadata");

                    b.Property<byte[]>("RowVersion");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryId");

                    b.ToTable("tbl_dictionary_value");
                });

            modelBuilder.Entity("SmartHome.Core.Entities.Entity.AppUserNodeLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("NodeId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("UserId");

                    b.ToTable("tbl_user_node_link");
                });

            modelBuilder.Entity("SmartHome.Core.Entities.Entity.ControlStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AppUserId");

                    b.Property<string>("AssemblyProduct")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("ContractAssembly")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<DateTime>("Created");

                    b.Property<int>("CreatedById");

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<bool>("IsActive");

                    b.Property<DateTime?>("Updated");

                    b.Property<int?>("UpdatedById");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("tbl_control_strategy");
                });

            modelBuilder.Entity("SmartHome.Core.Entities.Entity.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApiKey")
                        .HasMaxLength(30);

                    b.Property<int?>("AppUserId");

                    b.Property<string>("BaseTopic")
                        .HasMaxLength(100);

                    b.Property<string>("ClientId")
                        .HasMaxLength(100);

                    b.Property<string>("ConfigMetadata")
                        .HasMaxLength(2147483647);

                    b.Property<int?>("ControlStrategyId");

                    b.Property<DateTime>("Created");

                    b.Property<int>("CreatedById");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("GatewayIpAddress")
                        .HasMaxLength(20);

                    b.Property<string>("IpAddress")
                        .HasMaxLength(20);

                    b.Property<string>("Login")
                        .HasMaxLength(40);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .HasMaxLength(40);

                    b.Property<int>("Port");

                    b.Property<byte[]>("RowVersion");

                    b.Property<DateTime?>("Updated");

                    b.Property<int?>("UpdatedById");

                    b.Property<string>("UriSchema")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("ControlStrategyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("tbl_node");
                });

            modelBuilder.Entity("SmartHome.Core.Entities.Entity.NodeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("NodeId");

                    b.Property<int>("PhysicalPropertyId");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("PhysicalPropertyId");

                    b.ToTable("tbl_node_data");
                });

            modelBuilder.Entity("SmartHome.Core.Entities.Entity.PhysicalProperty", b =>
                {
                    b.Property<int>("Id");

                    b.Property<bool>("IsComplex");

                    b.Property<string>("Magnitude");

                    b.Property<string>("Name");

                    b.Property<string>("Unit");

                    b.HasKey("Id");

                    b.ToTable("tbl_physical_property");
                });

            modelBuilder.Entity("SmartHome.Core.Entities.Entity.PhysicalPropertyControlStrategyLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ControlStrategyId");

                    b.Property<int>("PhysicalPropertyId");

                    b.HasKey("Id");

                    b.HasIndex("ControlStrategyId");

                    b.HasIndex("PhysicalPropertyId");

                    b.ToTable("tbl_physicalproperty_controlstrategy_link");
                });

            modelBuilder.Entity("SmartHome.Core.Entities.Entity.UiConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data");

                    b.Property<byte[]>("RowVersion");

                    b.Property<int>("Type");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tbl_ui_configuration");
                });

            modelBuilder.Entity("SmartHome.Core.Entities.Role.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("tbl_role");
                });

            modelBuilder.Entity("SmartHome.Core.Entities.SchedulingEntity.JobStatusEntity", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("tbl_scheduling_job_status");
                });

            modelBuilder.Entity("SmartHome.Core.Entities.SchedulingEntity.JobType", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("AssemblyName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("FullyQualifiedName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("tbl_scheduling_job_type");
                });

            modelBuilder.Entity("SmartHome.Core.Entities.SchedulingEntity.ScheduleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<int>("CreatedById");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("JobGroup");

                    b.Property<string>("JobName")
                        .IsRequired();

                    b.Property<int>("JobStatusEntityId");

                    b.Property<int>("JobTypeId");

                    b.Property<string>("Name")
                        .HasMaxLength(255);

                    b.Property<byte[]>("RowVersion");

                    b.Property<int>("ScheduleTypeid");

                    b.Property<string>("SerializedJobSchedule");

                    b.Property<DateTime?>("Updated");

                    b.Property<int?>("UpdatedById");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("JobStatusEntityId");

                    b.HasIndex("JobTypeId");

                    b.HasIndex("ScheduleTypeid");

                    b.HasIndex("UpdatedById");

                    b.ToTable("tbl_scheduling_schedules");
                });

            modelBuilder.Entity("SmartHome.Core.Entities.SchedulingEntity.ScheduleType", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("AssemblyName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("FullyQualifiedName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("tbl_scheduling_schedule_type");
                });

            modelBuilder.Entity("SmartHome.Core.Entities.User.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<int?>("ActivatedById");

                    b.Property<DateTime>("ActivationDate");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("ActivatedById");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("tbl_user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("SmartHome.Core.Entities.Role.AppRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SmartHome.Core.Entities.User.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SmartHome.Core.Entities.User.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("SmartHome.Core.Entities.Role.AppRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SmartHome.Core.Entities.User.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SmartHome.Core.Entities.User.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SmartHome.Core.Entities.DictionaryEntity.DictionaryValue", b =>
                {
                    b.HasOne("SmartHome.Core.Entities.DictionaryEntity.Dictionary", "Dictionary")
                        .WithMany("Values")
                        .HasForeignKey("DictionaryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SmartHome.Core.Entities.Entity.AppUserNodeLink", b =>
                {
                    b.HasOne("SmartHome.Core.Entities.Entity.Node", "Node")
                        .WithMany("AllowedUsers")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SmartHome.Core.Entities.User.AppUser", "User")
                        .WithMany("EligibleNodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SmartHome.Core.Entities.Entity.ControlStrategy", b =>
                {
                    b.HasOne("SmartHome.Core.Entities.User.AppUser")
                        .WithMany("CreatedControlStrategies")
                        .HasForeignKey("AppUserId");

                    b.HasOne("SmartHome.Core.Entities.User.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SmartHome.Core.Entities.User.AppUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("SmartHome.Core.Entities.Entity.Node", b =>
                {
                    b.HasOne("SmartHome.Core.Entities.User.AppUser")
                        .WithMany("CreatedNodes")
                        .HasForeignKey("AppUserId");

                    b.HasOne("SmartHome.Core.Entities.Entity.ControlStrategy", "ControlStrategy")
                        .WithMany("Nodes")
                        .HasForeignKey("ControlStrategyId");

                    b.HasOne("SmartHome.Core.Entities.User.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SmartHome.Core.Entities.User.AppUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("SmartHome.Core.Entities.Entity.NodeData", b =>
                {
                    b.HasOne("SmartHome.Core.Entities.Entity.Node", "Node")
                        .WithMany("NodeData")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SmartHome.Core.Entities.Entity.PhysicalProperty", "PhysicalProperty")
                        .WithMany()
                        .HasForeignKey("PhysicalPropertyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SmartHome.Core.Entities.Entity.PhysicalPropertyControlStrategyLink", b =>
                {
                    b.HasOne("SmartHome.Core.Entities.Entity.ControlStrategy", "ControlStrategy")
                        .WithMany("PhysicalProperties")
                        .HasForeignKey("ControlStrategyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SmartHome.Core.Entities.Entity.PhysicalProperty", "PhysicalProperty")
                        .WithMany("ControlStrategies")
                        .HasForeignKey("PhysicalPropertyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SmartHome.Core.Entities.Entity.UiConfiguration", b =>
                {
                    b.HasOne("SmartHome.Core.Entities.User.AppUser", "User")
                        .WithMany("UiConfiguration")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SmartHome.Core.Entities.SchedulingEntity.ScheduleEntity", b =>
                {
                    b.HasOne("SmartHome.Core.Entities.User.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SmartHome.Core.Entities.SchedulingEntity.JobStatusEntity", "JobStatusEntity")
                        .WithMany()
                        .HasForeignKey("JobStatusEntityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SmartHome.Core.Entities.SchedulingEntity.JobType", "JobType")
                        .WithMany()
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SmartHome.Core.Entities.SchedulingEntity.ScheduleType", "ScheduleType")
                        .WithMany()
                        .HasForeignKey("ScheduleTypeid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SmartHome.Core.Entities.User.AppUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");
                });

            modelBuilder.Entity("SmartHome.Core.Entities.User.AppUser", b =>
                {
                    b.HasOne("SmartHome.Core.Entities.User.AppUser", "ActivatedBy")
                        .WithMany()
                        .HasForeignKey("ActivatedById");
                });
#pragma warning restore 612, 618
        }
    }
}
